# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestInputSearchText():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_inputSearchText(self):
    # Test name: InputSearchText
    # Step # | name | target | value
    # 1 | open | /verify | 
    self.driver.get("https://dlims.punjab.gov.pk/verify")
    # 2 | setWindowSize | 1936x1168 | 
    self.driver.set_window_size(1936, 1168)
    # 3 | click | id=cnicInput | 
    self.driver.find_element(By.ID, "cnicInput").click()
    # 4 | click | id=cnicInput | 
    self.driver.find_element(By.ID, "cnicInput").click()
    # 5 | type | id=cnicInput | 3440293014149
    self.driver.find_element(By.ID, "cnicInput").send_keys("3440293014149")
    # 6 | click | id=licenseNumber | 
    self.driver.find_element(By.ID, "licenseNumber").click()
    # 7 | type | id=licenseNumber | MN-23-3297
    self.driver.find_element(By.ID, "licenseNumber").send_keys("MN-23-3297")
    # 8 | click | id=captcha | 
    self.driver.find_element(By.ID, "captcha").click()
    # 9 | type | id=captcha | enp2pq
    self.driver.find_element(By.ID, "captcha").send_keys("enp2pq")
    # 10 | click | xpath=//td | 
    self.driver.find_element(By.XPATH, "//td").click()
    # 11 | click | xpath=//td[2] | 
    self.driver.find_element(By.XPATH, "//td[2]").click()
    # 12 | click | xpath=//td[3] | 
    self.driver.find_element(By.XPATH, "//td[3]").click()
    # 13 | click | xpath=//tr[2]/td | 
    self.driver.find_element(By.XPATH, "//tr[2]/td").click()
    # 14 | click | xpath=//table[2]/tbody/tr/td | 
    self.driver.find_element(By.XPATH, "//table[2]/tbody/tr/td").click()
    # 15 | click | xpath=//table[2]/tbody/tr/td[2] | 
    self.driver.find_element(By.XPATH, "//table[2]/tbody/tr/td[2]").click()
    # 16 | click | xpath=//table[2]/tbody/tr/td[3] | 
    self.driver.find_element(By.XPATH, "//table[2]/tbody/tr/td[3]").click()
    # 17 | click | xpath=//table[2]/tbody/tr[2]/td[3] | 
    self.driver.find_element(By.XPATH, "//table[2]/tbody/tr[2]/td[3]").click()
    # 18 | click | xpath=//table[2]/tbody/tr[2]/td[2] | 
    self.driver.find_element(By.XPATH, "//table[2]/tbody/tr[2]/td[2]").click()
    # 19 | click | xpath=//table[2]/tbody/tr[2]/td | 
    self.driver.find_element(By.XPATH, "//table[2]/tbody/tr[2]/td").click()
    # 20 | click | id=submit-btn | 
    self.driver.find_element(By.ID, "submit-btn").click()
  
